name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Sync version with Tag
        run: |
          CLEAN_VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')
          npm version $CLEAN_VERSION --no-git-tag-version
      - name: Build
        run: npm run build
      - name: Package Extension
        run: npx @vscode/vsce package
      - name: Rename Release Asset
        run: mv *.vsix copilot-quota-alert-${{ github.ref_name }}.vsix
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.vsix"
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
